openapi: 3.0.3
info:
  title: Instructions
  description: Specifications of the instructions API endpoints.
  version: 1.0.0
tags:
  - name: Communication
    description: Endpoints relating to communication, especially between dispatch manager and driver of a vehicle.
servers:
  - url: /fl
  - url: /
paths:
  /gw/instructionTemplates:
    summary: Returns the instruction templates (for predefined and / or user-defined instructions) queried.
    get:
      tags:
        - Communication
      description:
        Retrieves data related to the instruction templates queried. The method shall be used with at least
        the tenant query parameter set (to a non-empty array). Note that currently, the contents of the response like
        the text property will be in the language which was used in the plan data.
      operationId: retrieveInstructionTemplates
      parameters:
        - $ref: "./common/parameters.yaml#/query/multipleTenants"
        - $ref: "./common/parameters.yaml#/header/Accept-Language-Required"
        - name: type
          in: query
          description:
            Type of instruction (message). 'PREDEFINED' stands for coded instructions predefined by the system,
            the templates for which cannot be altered. 'USER_DEFINED' stands for custom text instructions defined by a
            user, the templates for which can be altered.
          schema:
            type: array
            items:
              $ref: "#/components/schemas/InstructionType"
      responses:
        200:
          description: The data of all known instruction templates matching the given parameters is returned.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InstructionTemplatesResponse"
        400:
          description: Will be returned if filtering parameter are missing as described above.
        403:
          $ref: "./common/responses.yaml#/NotAuthorizedForTenants"
        404:
          $ref: "./common/responses.yaml#/UnknownTenant"
    post:
      tags:
        - Communication
      description: Creates a new user-defined instruction template.
      operationId: createInstructionTemplate
      requestBody:
        required: true
        description: All readonly properties will be ignored.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InstructionTemplate"
      responses:
        200:
          description:
            Will be returned if the template was created successfully. The returned instruction template will
            contain the identification property and thus the UID of the template.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InstructionTemplate"
        400:
          description: Will be returned if the request body is missing or does not contain a valid instruction template.
        403:
          description:
            __Upcoming after introduction of auth__ Will be returned if the client requests to create an
            instruction template for a tenant that it is not authorized for.
        404:
          $ref: "./common/responses.yaml#/UnknownTenant"
        500:
          description:
            Will be returned if, for any other reason than a malformed request, there was a failure to
            save the instruction template to the database on the server side.
    put:
      tags:
        - Communication
      description: Replaces a user-defined instruction template.
      operationId: ReplacesInstructionTemplate
      parameters:
        - name: uid
          in: path
          description:
            UID of the instruction template one wants to replace. Must contain the UID as provided in an
            InstructionTemplateIdentification.
          required: true
          schema:
            type: string
      requestBody:
        required: true
        description: All readonly properties will be ignored.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/InstructionTemplate"
      responses:
        200:
          description: Will be returned if the template was replaced successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InstructionTemplate"
        400:
          $ref: "#/components/responses/MalformedInstructionUID"
        403:
          description:
            __Upcoming after introduction of auth__ Will be returned if the client requests to replace an
            instruction template for a tenant that it is not authorized for.
        404:
          description: Will be returned if the referenced instruction template cannot be found.
    delete:
      tags:
        - Communication
      description:
        Deletes a single instruction template. The instruction template must be of type USER_DEFINED.
        Templates of other types cannot be deleted.
      operationId: deleteInstructionTemplate
      parameters:
        - name: uid
          in: path
          description:
            UID of the instruction template to be deleted. Must contain the UID as provided in an
            InstructionTemplateIdentification.
          required: true
          schema:
            type: string
      responses:
        200:
          description:
            Will be returned if the referenced instruction template was successfully deleted. This code will
            also be returned if the instruction template has already been deleted before the delete request being
            responded to or if it has never existed at all.
        400:
          $ref: "#/components/responses/MalformedInstructionUID"
        403:
          description:
            Will be returned if the referenced instruction template is not of type USER_DEFINED and therefore
            cannot be deleted.
            __Upcoming after introduction of auth__ Will be returned as well if the client requests to delete an
            instruction template belonging to a tenant he is not authorized for.
  /gw/instructions:
    summary: Sends an instruction (predefined or user-defined instruction).
    post:
      tags:
        - Communication
      description:
        Sends an instruction (predefined or user-defined instruction). The request must at least contain the
        UID of a predefined instruction if the request is of type 'PREDEFINED'. If the request is of type
        'USER_DEFINED', then wanting to use a template and not changing the text can be expressed by using the uid of
        the desired template. The other cases of type 'USER_DEFINED' shall set the text property. The text will not be
        internationalized and will be presented to every user as it was given, independently of an individual user's
        language.
      operationId: sendInstruction
      requestBody:
        description: All readonly properties will be ignored.
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Instruction"
      responses:
        200:
          description:
            Will be returned if the instruction was sent. The sent message with all its data is present in
            the response body.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Instruction"
        400:
          description:
            Will be returned if the request body is missing, does not contain the required information or
            exceeds any limitations (e.g. number of characters of the displayText). It may also be returned if the
            given UID of an instruction template cannot be matched to an instruction template in the database.
        403:
          description:
            __Upcoming after introduction of auth__ Will be returned if the client tries to send an
            instruction for a tenant it is not authorized for.
        404:
          $ref: "./common/responses.yaml#/UnknownTenant"
        500:
          description:
            Will be returned if, for any reason other than a malformed request, the sending of the
            instruction failed. The client may try again although the actual reason for the previous request's failure
            might be something that cannot be influenced by the client. A fixed number of retries would be advisable.
components:
  schemas:
    InstructionType:
      type: string
      enum:
        - PREDEFINED
        - USER_DEFINED
    InstructionTemplatesResponse:
      type: object
      properties:
        data:
          $ref: "#/components/schemas/InstructionTemplatesResponseData"
    InstructionTemplatesResponseData:
      type: object
      properties:
        predefinedTemplates:
          type: array
          items:
            $ref: "#/components/schemas/InstructionTemplate"
        userDefinedTemplates:
          type: array
          items:
            $ref: "#/components/schemas/InstructionTemplate"
    InstructionTemplate:
      type: object
      description: The identification property of an instruction template is read-only.
      required:
        - tenant
        - text
      properties:
        tenant:
          type: string
        identification:
          $ref: "#/components/schemas/InstructionTemplateIdentification"
        text:
          type: string
        driverAcknowledgement:
          type: boolean
          description: If present, indicates to the preset whether the addressed driver shall acknowledge the receipt.
    Instruction:
      type: object
      properties:
        tenant:
          type: string
        template:
          $ref: "#/components/schemas/InstructionTemplateIdentification"
        text:
          type: string
          description: not applicable when type is 'PREDEFINED'
        driverAcknowledgement:
          type: boolean
          description: Indicates whether the addressed driver shall acknowledge the receipt.
        recipients:
          $ref: "#/components/schemas/InstructionRecipients"
    InstructionTemplateIdentification:
      type: object
      properties:
        type:
          $ref: "#/components/schemas/InstructionType"
        uid:
          type: string
    InstructionRecipients:
      type: object
      properties:
        vehicles:
          type: array
          items:
            $ref: "./common/schemas.yaml#/VehicleIdentification"
  responses:
    MalformedInstructionUID:
      description:
        Will be returned if the given UID of the instruction template was not provided in the proper
        format or the service had any other issue while processing it.
