export type InternalNotification = {
  id: number;
  message: string;
  date: Date;
  read?: boolean;
};

export type Filter = {
  id: number;
  name: string;
  schluessel: string;
  metrik: string;
  filterZeit: number[];
  filterLinie: string[];
  filterUnternehmen: string[];
  chartTyp: string;
};

export const useNotifications = () =>
  useState<InternalNotification[]>("notifications", () => []);

export const useAlleLinien = () =>
  useState<number[]>("alleLinien", () => [1, 2, 3, 4]);

export const useAlleUnternehmen = () =>
  useState<string[]>("alleUnternehmen", () => ["IVU", "IVB"]);

export const useFilter = () =>
  useState<Filter[]>("filters", () => [
    {
      id: 1,
      name: "Anzahl Fahrten pro Unternehmen",
      schluessel: "Unternehmen",
      metrik: "Fahrten",
      filterZeit: [-3000, 6000],
      filterLinie: [
        "IVU/1",
        "IVU/101",
        "IVU/102",
        "IVU/103",
        "IVU/104",
        "IVU/105",
        "IVU/106",
        "IVU/107",
        "IVU/11",
        "IVU/111",
        "IVU/119",
        "IVU/121",
        "IVU/122",
        "IVU/123",
        "IVU/124",
        "IVU/131",
        "IVU/132",
        "IVU/133",
        "IVU/141",
        "IVU/142",
        "IVU/151",
        "IVU/16",
        "IVU/196",
        "IVU/2",
        "IVU/201",
        "IVU/202",
        "IVU/3",
        "IVU/31",
        "IVU/32",
        "IVU/5",
        "IVU/51",
        "IVU/521",
        "IVU/531",
        "IVU/54",
        "IVU/551",
        "IVU/56",
        "IVU/57",
        "IVU/581",
        "IVU/59",
        "IVU/6",
        "IVU/60",
        "IVU/61",
        "IVU/62",
        "IVU/66",
        "IVU/7",
        "IVU/73",
        "IVU/74",
        "IVU/75",
        "IVU/76",
        "IVU/87",
        "IVU/94",
        "STO/100",
        "STO/11",
        "STO/50",
        "STO/52",
        "STO/53",
        "STO/55",
        "STO/58",
        "STO/63",
        "STO/64",
        "STO/80",
        "STO/81",
        "STO/82",
        "STO/83",
        "STO/84",
        "STO/85",
        "STO/86",
        "STO/89",
        "STO/891",
        "STO/98",
        "STO/99",
      ],
      filterUnternehmen: ["IVU", "STO"],
      chartTyp: "Bar Chart",
    },
    {
      id: 2,
      name: "Gesamtzustand",
      schluessel: "Zustand",
      metrik: "Fahrten",
      filterZeit: [-3000, 6000],
      filterLinie: [
        "IVU/1",
        "IVU/101",
        "IVU/102",
        "IVU/103",
        "IVU/104",
        "IVU/105",
        "IVU/106",
        "IVU/107",
        "IVU/11",
        "IVU/111",
        "IVU/119",
        "IVU/121",
        "IVU/122",
        "IVU/123",
        "IVU/124",
        "IVU/131",
        "IVU/132",
        "IVU/133",
        "IVU/141",
        "IVU/142",
        "IVU/151",
        "IVU/16",
        "IVU/196",
        "IVU/2",
        "IVU/201",
        "IVU/202",
        "IVU/3",
        "IVU/31",
        "IVU/32",
        "IVU/5",
        "IVU/51",
        "IVU/521",
        "IVU/531",
        "IVU/54",
        "IVU/551",
        "IVU/56",
        "IVU/57",
        "IVU/581",
        "IVU/59",
        "IVU/6",
        "IVU/60",
        "IVU/61",
        "IVU/62",
        "IVU/66",
        "IVU/7",
        "IVU/73",
        "IVU/74",
        "IVU/75",
        "IVU/76",
        "IVU/87",
        "IVU/94",
        "STO/100",
        "STO/11",
        "STO/50",
        "STO/52",
        "STO/53",
        "STO/55",
        "STO/58",
        "STO/63",
        "STO/64",
        "STO/80",
        "STO/81",
        "STO/82",
        "STO/83",
        "STO/84",
        "STO/85",
        "STO/86",
        "STO/89",
        "STO/891",
        "STO/98",
        "STO/99",
      ],
      filterUnternehmen: ["IVU", "STO"],
      chartTyp: "Pie",
    },
    {
      id: 3,
      name: "Zustand der Linie IVU/105",
      schluessel: "Zustand",
      metrik: "Fahrten",
      filterZeit: [-3000, 6000],
      filterLinie: ["IVU/105"],
      filterUnternehmen: ["IVU", "STO"],
      chartTyp: "Pie",
    },
    {
      id: 4,
      name: "Anteil verspäteter Fahrten pro Unternehmen",
      schluessel: "Unternehmen",
      metrik: "Anteil der Fahrten unter Zeitfilter",
      filterZeit: [-3000, -2],
      filterLinie: [
        "IVU/1",
        "IVU/101",
        "IVU/102",
        "IVU/103",
        "IVU/104",
        "IVU/105",
        "IVU/106",
        "IVU/107",
        "IVU/11",
        "IVU/111",
        "IVU/119",
        "IVU/121",
        "IVU/122",
        "IVU/123",
        "IVU/124",
        "IVU/131",
        "IVU/132",
        "IVU/133",
        "IVU/141",
        "IVU/142",
        "IVU/151",
        "IVU/16",
        "IVU/196",
        "IVU/2",
        "IVU/201",
        "IVU/202",
        "IVU/3",
        "IVU/31",
        "IVU/32",
        "IVU/5",
        "IVU/51",
        "IVU/521",
        "IVU/531",
        "IVU/54",
        "IVU/551",
        "IVU/56",
        "IVU/57",
        "IVU/581",
        "IVU/59",
        "IVU/6",
        "IVU/60",
        "IVU/61",
        "IVU/62",
        "IVU/66",
        "IVU/7",
        "IVU/73",
        "IVU/74",
        "IVU/75",
        "IVU/76",
        "IVU/87",
        "IVU/94",
        "STO/100",
        "STO/11",
        "STO/50",
        "STO/52",
        "STO/53",
        "STO/55",
        "STO/58",
        "STO/63",
        "STO/64",
        "STO/80",
        "STO/81",
        "STO/82",
        "STO/83",
        "STO/84",
        "STO/85",
        "STO/86",
        "STO/89",
        "STO/891",
        "STO/98",
        "STO/99",
      ],
      filterUnternehmen: ["IVU", "STO"],
      chartTyp: "Bar",
    },
    {
      id: 5,
      name: "Durchschnittliche Abweichung pro Linie",
      schluessel: "Linie",
      metrik: "Durchschnittliche Abweichung",
      filterZeit: [-3000, 6000],
      filterLinie: [
        "IVU/1",
        "IVU/101",
        "IVU/102",
        "IVU/103",
        "IVU/104",
        "IVU/105",
        "IVU/106",
        "IVU/107",
        "IVU/11",
        "IVU/111",
        "IVU/119",
        "IVU/121",
        "IVU/122",
        "IVU/123",
        "IVU/124",
        "IVU/131",
        "IVU/132",
        "IVU/133",
        "IVU/141",
        "IVU/142",
        "IVU/151",
        "IVU/16",
        "IVU/196",
        "IVU/2",
        "IVU/201",
        "IVU/202",
        "IVU/3",
        "IVU/31",
        "IVU/32",
        "IVU/5",
        "IVU/51",
        "IVU/521",
        "IVU/531",
        "IVU/54",
        "IVU/551",
        "IVU/56",
        "IVU/57",
        "IVU/581",
        "IVU/59",
        "IVU/6",
        "IVU/60",
        "IVU/61",
        "IVU/62",
        "IVU/66",
        "IVU/7",
        "IVU/73",
        "IVU/74",
        "IVU/75",
        "IVU/76",
        "IVU/87",
        "IVU/94",
        "STO/100",
        "STO/11",
        "STO/50",
        "STO/52",
        "STO/53",
        "STO/55",
        "STO/58",
        "STO/63",
        "STO/64",
        "STO/80",
        "STO/81",
        "STO/82",
        "STO/83",
        "STO/84",
        "STO/85",
        "STO/86",
        "STO/89",
        "STO/891",
        "STO/98",
        "STO/99",
      ],
      filterUnternehmen: ["IVU", "STO"],
      chartTyp: "Bar",
    },
    {
      id: 5,
      name: "Abweichung der Linie IVU/101",
      schluessel: "Minuten",
      metrik: "Fahrten",
      filterZeit: [-3000, 6000],
      filterLinie: ["IVU/101"],
      filterUnternehmen: ["IVU", "STO"],
      chartTyp: "Bar",
    },
  ]);
